# Generated by Django 6.1.1 on 2026-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
