# Generated by Django 6.1.1 on 2026-09-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='candidate.candidate')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='voter.voter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
